Args = --no-fallback \
       -H:+ReportExceptionStackTraces \
       --enable-url-protocols=http,https \
       --initialize-at-build-time=jexer.bits.Color \
       --initialize-at-build-time=jexer.bits.GraphicsChars
